name: Build

on:
  push:
    branches: [main]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"
      
      - name: Download Static FFmpeg & FFprobe (Windows)
        run: |
          curl -L -o ffmpeg.zip https://github.com/ffbinaries/ffbinaries-prebuilt/releases/download/v6.1/ffmpeg-6.1-win-64.zip
          curl -L -o ffprobe.zip https://github.com/ffbinaries/ffbinaries-prebuilt/releases/download/v6.1/ffprobe-6.1-win-64.zip
          Expand-Archive ffmpeg.zip -DestinationPath . -Force
          Expand-Archive ffprobe.zip -DestinationPath . -Force
          
      - name: Install Python deps
        run: pip install pyinstaller yt-dlp
        
      - name: Build
        run: |
          pyinstaller --onefile --windowed --name you2tomp3 `
            --add-binary "ffmpeg.exe;." `
            --add-binary "ffprobe.exe;." `
            src/main.py
            
      - uses: actions/upload-artifact@v5
        with:
          name: yt-mp3-windows
          path: dist/you2tomp3.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"
          
      - name: Download Static FFmpeg & FFprobe (macOS)
        run: |
          curl -L -o ffmpeg.zip https://github.com/ffbinaries/ffbinaries-prebuilt/releases/download/v6.1/ffmpeg-6.1-osx-64.zip
          curl -L -o ffprobe.zip https://github.com/ffbinaries/ffbinaries-prebuilt/releases/download/v6.1/ffprobe-6.1-osx-64.zip
          unzip -o ffmpeg.zip
          unzip -o ffprobe.zip
          
      - name: Install Python deps
        run: pip install pyinstaller yt-dlp
        
      - name: Build
        run: |
          pyinstaller --onefile --windowed --name you2tomp3 \
            --add-binary "ffmpeg:." \
            --add-binary "ffprobe:." \
            src/main.py
            
      - uses: actions/upload-artifact@v5
        with:
          name: yt-mp3-macos
          path: dist/you2tomp3.app

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"
          
      - name: Download Static FFmpeg & FFprobe (Linux)
        run: |
          curl -L -o ffmpeg.zip https://github.com/ffbinaries/ffbinaries-prebuilt/releases/download/v6.1/ffmpeg-6.1-linux-64.zip
          curl -L -o ffprobe.zip https://github.com/ffbinaries/ffbinaries-prebuilt/releases/download/v6.1/ffprobe-6.1-linux-64.zip
          unzip -o ffmpeg.zip
          unzip -o ffprobe.zip
          
      - name: Install Python deps
        run: pip install pyinstaller yt-dlp
        
      - name: Build
        run: |
          pyinstaller --onefile --name you2tomp3 \
            --add-binary "ffmpeg:." \
            --add-binary "ffprobe:." \
            src/main.py
            
      - uses: actions/upload-artifact@v5
        with:
          name: yt-mp3-linux
          path: dist/you2tomp3