name: Build

on:
  push:
    branches: [main]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"
      - name: Install ffmpeg
        run: choco install ffmpeg -y
      - name: Install Python deps
        run: pip install pyinstaller yt-dlp
      - name: Build
        run: |
          $ffmpeg = (Get-Command ffmpeg).Source
          $ffprobe = (Get-Command ffprobe).Source
          $ffplay = (Get-Command ffplay).Source
          pyinstaller --onefile --windowed --name you2tomp3 `
            --add-binary "${ffmpeg};ffmpeg" `
            --add-binary "${ffprobe};ffmpeg" `
            --add-binary "${ffplay};ffmpeg" `
            src/main.py
      - uses: actions/upload-artifact@v5
        with:
          name: yt-mp3-windows
          path: dist/you2tomp3.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"
      - name: Install ffmpeg
        run: brew install ffmpeg
      - name: Install Python deps
        run: pip install pyinstaller yt-dlp
      - name: Build
        run: |
          pyinstaller --onefile --windowed --name you2tomp3 \
            --add-binary "$(which ffmpeg):ffmpeg" \
            --add-binary "$(which ffprobe):ffmpeg" \
            --add-binary "$(which ffplay):ffmpeg" \
            src/main.py
      - uses: actions/upload-artifact@v5
        with:
          name: yt-mp3-macos
          path: dist/you2tomp3

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"
      - name: Install ffmpeg
        run: sudo apt-get install -y ffmpeg
      - name: Install Python deps
        run: pip install pyinstaller yt-dlp
      - name: Build
        run: |
          pyinstaller --onefile --name you2tomp3 \
            --add-binary "$(which ffmpeg):ffmpeg" \
            --add-binary "$(which ffprobe):ffmpeg" \
            --add-binary "$(which ffplay):ffmpeg" \
            src/main.py
      - uses: actions/upload-artifact@v5
        with:
          name: yt-mp3-linux
          path: dist/you2tomp3